// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    // A URL do datasource é configurada via adapter no runtime (lib/prisma.ts)
    // Isso evita erro no prisma generate quando DATABASE_URL não está disponível
});
